language: java

env:
  - LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8

jdk:
  - oraclejdk8
  - openjdk8

cache:
  directories:
    - $HOME/.m2

script: mvn clean verify checkstyle:checkstyle -e -Dmaven.javadoc.skip=true -Pjenkins

